spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management_system?useSSL=false
    username: root
    password:

  jpa:
    properties:
      hibernate:
        # MySQL5InnoDBDialect Deprecated!!
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update